version: "2"

# options for analysis running
run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # include test files or not, default is true
  tests: true

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in types assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 2
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 2
  gocritic:
    disabled-checks:
      - whyNoLint # https://github.com/go-critic/go-critic/issues/1063
      - importShadow
      - sloppyReassign
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # See https://github.com/go-critic/go-critic#usage -> section "Tags".
    # Default: []
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    settings:
      # Must be valid enabled check name.
      captLocal:
        # Whether to restrict checker to params only.
        # Default: true
        paramsOnly: false
      elseif:
        # Whether to skip balanced if-else pairs.
        # Default: true
        skipBalanced: false
      hugeParam:
        # Size in bytes that makes the warning trigger.
        # Default: 80
        sizeThreshold: 70
      nestingReduce:
        # Min number of statements inside a branch to trigger a warning.
        # Default: 5
        bodyWidth: 4
      rangeExprCopy:
        # Size in bytes that makes the warning trigger.
        # Default: 512
        sizeThreshold: 516
        # Whether to check test functions
        # Default: true
        skipTestFuncs: false
      rangeValCopy:
        # Size in bytes that makes the warning trigger.
        # Default: 128
        sizeThreshold: 32
        # Whether to check test functions.
        # Default: true
        skipTestFuncs: false
      ruleguard:
        # Enable debug to identify which 'Where' condition was rejected.
        debug: emptyDecl
        # Comma-separated list of disabled groups or skip empty to enable everything.
        disable: myGroupName,#myTagName
        # Comma-separated list of enabled groups or skip empty to enable everything.
        enable: myGroupName,#myTagName
        # Determines the behavior when an error occurs while parsing ruleguard files.
        failOn: dsl
      tooManyResultsChecker:
        # Maximum number of results.
        # Default: 5
        maxResults: 10
      truncateCmp:
        # Whether to skip int/uint/uintptr types.
        # Default: true
        skipArchDependent: false
      underef:
        # Whether to skip (*x).method() calls where x is a pointer receiver.
        # Default: true
        skipRecvDeref: false
      unnamedResult:
        # Whether to check exported functions.
        # Default: false
        checkExported: true
  gomoddirectives:
    replace-allow-list:
      - xorm.io/xorm
    replace-local: true
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-rules:
      - cancelled
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: nestif
        disabled: true
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    check-exported: false

linters:
  # Enable all linters by default
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - gochecknoglobals
    - gocognit
    - gocritic
    - godot
    - gosec
    - interfacebloat
    - intrange
    - ireturn
    - maintidx
    - mnd
    - nonamedreturns
    - paralleltest
    - perfsprint
    - predeclared
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - nestif
  settings:
    modernize:
      # Deactivate check "interface{} → any"
      disable:
        - any
  exclusions:
    # Enable exclusions for generated files
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - nosnakecase
        text: (?:_[a-z]+(?:[A-Z](?:[a-z\d]+|[A-Z\d]+))+|(?:[A-Z][a-z\d]+|[A-Z][A-Z\d]+)+_(?:(?:[A-Z][a-z\d]+|[A-Z\d][A-Z\d]+)_?)+)
      - path: (.+)\.go$
        text: has been deprecated since Go 1.16
      - linters:
          - goconst
        path: (.+)_test\.go

issues:
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # Default is false.
  new: false

# output formatters configuration
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/ydb-platform/gorm-driver) # Custom section: groups all imports with the specified Prefix.
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true
    gofumpt:
      module-path: github.com/ydb-platform/gorm-driver
    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes:
        - github.com/ydb-platform/gorm-driver
  exclusions:
    # Enable exclusions for generated files
    generated: lax
